// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnokwebfjxttjfzqhxlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indub2t3ZWJmanh0dGpmenFoeGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwMDI5NTEsImV4cCI6MjA4OTU3ODk1MX0.DcPfpplPOVy23fQXpnovRFUrddzGUXbjFOGEENVDvdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});